/**
 * IRepository<T> — Database adapter contract.
 *
 * Services depend ONLY on this interface, never on a concrete storage class.
 * The current implementation is JsonRepository (backed by JSON files).
 *
 * Migration path:
 *   1. Create PostgresRepository<T> implements IRepository<T> using pg/Prisma.
 *   2. Replace `new JsonRepository<X>('collection')` with
 *      `new PostgresRepository<X>(pgClient, 'table')` in each service.
 *   3. No changes needed in the service layer — it already depends only on
 *      this interface.
 *
 * Supporting types are re-exported here so callers only need this one import.
 */

import type {
  BaseEntity,
  Predicate,
  PaginateOptions,
  PageResult,
} from '../storage/JsonStorageService';

export type { BaseEntity, Predicate, PaginateOptions, PageResult };

export interface IRepository<T extends BaseEntity> {

  // ── Query ──────────────────────────────────────────────────────────────────

  /** Return all records, optionally filtered by a predicate. */
  findAll(filter?: Predicate<T>): T[];

  /** Return record by primary key, or null. */
  findById(id: string): T | null;

  /** Return the first record matching a predicate, or null. */
  findOne(predicate: Predicate<T>): T | null;

  /** Return all records matching a predicate. */
  findMany(predicate: Predicate<T>): T[];

  /** Count records, optionally scoped to a predicate. */
  count(predicate?: Predicate<T>): number;

  /** Return true if at least one record satisfies the predicate. */
  exists(predicate: Predicate<T>): boolean;

  /**
   * Paginate with optional filter + sort.
   * SQL adapters: map to SELECT … LIMIT/OFFSET with ORDER BY.
   */
  paginate(options?: PaginateOptions<T>): PageResult<T>;

  // ── Mutation ───────────────────────────────────────────────────────────────

  /**
   * Insert a new record.
   * id, createdAt, updatedAt are auto-generated by the adapter.
   */
  create(data: Omit<T, 'id' | 'createdAt' | 'updatedAt'>): T;

  /**
   * Patch a record by primary key.
   * updatedAt is always refreshed. id and createdAt are immutable.
   * Returns the updated record, or null if not found.
   */
  updateById(id: string, patch: Partial<Omit<T, 'id' | 'createdAt'>>): T | null;

  /**
   * Update the first record satisfying a predicate.
   * Returns the updated record, or null if no match.
   */
  updateOne(
    predicate: Predicate<T>,
    patch: Partial<Omit<T, 'id' | 'createdAt'>>,
  ): T | null;

  /** Hard-delete by primary key. Returns true if a record was removed. */
  deleteById(id: string): boolean;

  /**
   * Soft-delete — sets isActive: false on the record.
   * Returns the updated record, or null if not found.
   */
  softDelete(id: string): T | null;

  /**
   * Atomic read-modify-write.
   *
   * JSON adapter: reads full collection → applies transform → writes back.
   * SQL adapter: use a DB-level transaction with SELECT FOR UPDATE.
   *
   * The transform receives a snapshot array and must return the new state.
   * Throwing inside transform cancels the write.
   */
  transaction(transform: (items: T[]) => T[]): T[];

  // ── Dev / test utilities ───────────────────────────────────────────────────

  /**
   * Insert seed records only when the collection is empty.
   * SQL adapters: run inside an upsert or skip if COUNT > 0.
   */
  seed(records: Omit<T, 'id' | 'createdAt' | 'updatedAt'>[]): void;

  /** Wipe the entire collection. Use only in tests or seed scripts. */
  clear(): void;
}
